#!/usr/bin/env perl

use strict;
use warnings;
use Data::Dumper qw(Dumper);

for my $username_or_uid (@ARGV ? @ARGV : `getent passwd` =~ /^[^:]+/msxg) {
    # Make sure the argument won't inadverently cause a shell to run commands.
    unless ($username_or_uid =~ /\w[\w-]/msx) {
        warn qq{$0: bad username or uid "$username_or_uid"\n};
        next;
    }

    if (`getent passwd $username_or_uid` =~ /^(?<user>[^:]+)
                                             :(?<pass>[^:]*)
                                             :(?<uid>\d+)
                                             :(?<gid>\d+)
                                             :(?<gecos>[^:]*)
                                             :(?<home>[^:]+)/msx) {
        print Dumper(\%+);
    } else {
        warn qq{$0: username or uid "$username_or_uid" not found\n};
    }
}
