#!/usr/bin/env perl

use strict;
use warnings;
use Data::Dumper qw(Dumper);
use English qw(PROGRAM_NAME);

sub display_passwd_record_hash {
    my ($name,
        $passwd,
        $uid,
        $gid,
        $quota,
        $comment,
        $gcos,
        $dir,
        $shell,
        $expire) = @_;

    print Dumper({
        user => $name,
        passwd => $passwd,
        uid => $uid,
        gid => $gid,
        gecos => $gcos,
        home => $dir,
        shell => $shell,
    });

    return;
}

sub query_one {
    my $username_or_uid = shift;

    my @pw = ($username_or_uid =~ /\A\d+\z/msx ? getpwuid $username_or_uid
                                               : getpwnam $username_or_uid);

    if (@pw) {
        display_passwd_record_hash(@pw);
    } else {
        warn qq{$PROGRAM_NAME: username or uid "$username_or_uid" not found\n};
    }

    return;
}

if (@ARGV) {
    for my $username_or_uid (@ARGV) {
        query_one($username_or_uid);
    }
} else {
    while (my @pw = getpwent) {
        display_passwd_record_hash(@pw);
    }
}
